name: test2

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Test1
        run: |
          # รันสคริปต์ Node.js และเก็บ output
          output=$(node dist/Test1.js)
          exit_code=$?  # จับ exit code ของคำสั่ง node

          echo "Output: $output"
          echo "Exit code: $exit_code"

          # ตรวจสอบรหัสสถานะ หากไม่เท่ากับ 0 ให้ workflow fail
          if [ $exit_code -ne 0 ]; then
            echo "Error: Test1 failed with exit code $exit_code"
            exit 1
          fi
